### ISSUE TITLE
Some functions are missing in this repo

### ISSUE THREAD

**Issue by Abbey4799** [nairoj/Probing-Simile-from-PLM#2]
Thank you very much for this repo! 
It seems that the functions '_parse_and_tokenize' and '_forward' in class SimileGenerator are missing. 
Appreciate any help you can offer with this.

**Comment by Abbey4799** [comment]
Oops, I fix this! The error is due to different versions of transformers. The code works fine.

**Comment by nairoj** [comment]
ok~
